Serialization
sberbank-ai-lab/RePlay pull request #22
Opened 2021-10-26 14:08 UTC by Darel13712

New module `model_handler` with functions `save` and `load`. Model is saved as a folder.
Also bumped version to 0.7.0

2021-11-03 14:15 UTC, AleXXL1986 requested changes

2021-11-03 15:04 UTC, Darel13712 commented on replay/model_handler.py
> +    with open(join(path, "init_args.json"), "r") as json_file:
If you try to load something that does not exist it will raise file not found error, exactly the error that should be displayed. The same thing happens with pickle, joblib or torch when you load non existing files. No one really checks if they exist before trying to load them.

2021-11-03 15:09 UTC, AleXXL1986 commented on replay/model_handler.py
> +    with open(join(path, "init_args.json"), "r") as json_file:
but user don't know  about internal structure and error won't be informative

2021-11-03 15:16 UTC, AleXXL1986 commented on replay/model_handler.py
> +    init_args = getfullargspec(eval(f"{name}.__init__")).args
import sys
getattr(sys.modules[__name__], "Foo")

2021-11-03 15:21 UTC, Darel13712 commented on replay/model_handler.py
> +    with open(join(path, "init_args.json"), "r") as json_file:
It is either a correct path, or it isn't. If it is a model folder, then it will be loaded.

2021-11-04 09:52 UTC, AleXXL1986 commented
rebase the branch, please

2021-11-04 12:51 UTC, Darel13712 commented
Will the squash suffice?

2021-11-05 12:46 UTC, AleXXL1986 commented
> Will the squash suffice?

No

2021-11-08 13:00 UTC, merged