dont cast to timestamp
sberbank-ai-lab/RePlay pull request #27
Opened 2021-11-01 16:05 UTC by Darel13712

solves #24

2021-11-03 08:09 UTC, monkey0head requested changes

2021-11-03 08:09 UTC, monkey0head commented on replay/splitters/log_splitter.py
> -        )
have a look at the docstring:
```
:param test_start: date ``yyyy-mm-dd`` or a
            fraction for test size to determine data automatically
```
with your changes `test start` should be datetime or int or float.
so you need to change docstring anyway

I also suggest to remain an opportunity to pass string in format ``yyyy-mm-dd`` and apply `.cast(TimestampType())` if test_start is str

2021-11-03 09:08 UTC, Darel13712 commented on replay/splitters/log_splitter.py
> -        )
But `str` type is not specified for this parameter as accepted in the docs 🤔

2021-11-04 09:50 UTC, AleXXL1986 commented on replay/splitters/log_splitter.py
> -        )
let's add `str` type to specified

2021-11-04 12:49 UTC, Darel13712 commented on replay/splitters/log_splitter.py
> -        )
It does not work with `str` yet because timestamp column is not converted in any way.

2021-11-08 10:29 UTC, monkey0head commented on replay/splitters/log_splitter.py
> -        )
> It does not work with `str` yet because timestamp column is not converted in any way.

could you explain the problem more clearly? 

I think, we assume that the users want to apply date splitter to dataset with the `timestamp` column of `TimestampType` or numeric type. If the column's type is a `StringType`, it is not our problem, it is the users problem. We have `datapreparator` to preprocess timestamp and it is a user's responsibility to preprocess the data.

2021-11-08 11:02 UTC, Darel13712 commented on replay/splitters/log_splitter.py
> -        )
Movielens has `int` timestamp. `test_start` is converted to `timestamp` but the column is not, so you get this error "can't compare int to timestamp".

2021-11-08 11:09 UTC, monkey0head commented on replay/splitters/log_splitter.py
> -        )
if you get a string as a `test_start`, you convert it to timestamp. if the column type is not TimestampType, well, it is not our fault.
Otherwise you treat numetic types as it is done currently without conversion to timestamp

2021-11-10 14:33 UTC, monkey0head approved these changes

2021-11-11 11:40 UTC, merged