optuna starts with the models parameters if within search borders
sberbank-ai-lab/RePlay pull request #34
Opened 2021-11-09 08:33 UTC by monkey0head

- Check if the model parameters lays within optimize search borders and, if so, add a trial with the model parameters
- tests rewritten to check different parameters's types processing and  different behaviour  in cases when models params lays within optimize search borders and not
- slim search space lower border raised
- `eval_quality` function detached to be able to recalculate objective value without optuna (not actually used separately for now)

2021-11-09 21:58 UTC, Darel13712 requested changes

2021-11-09 21:58 UTC, Darel13712 commented on pyproject.toml
> +statsmodels = "*"
Do we still need statsmodels? I thought it was used only in Wilson.

2021-11-09 21:58 UTC, Darel13712 commented on replay/models/base_rec.py
> +                if value < borders[0] or value > borders[1]:
This is redundant. Please change to something like
```python
extra_category =  param_type == "categorical" and value not in borders
param_out_of_bounds = param_type != "categorical" and (value < borders[0] or value > borders[1])
if extra_category or param_out_of_bounds:
    outside_search_space[param] = {
                        "borders": borders,
                        "value": value,
                    }
```

2021-11-09 21:58 UTC, Darel13712 commented on replay/optuna_objective.py
> +def eval_quality(
What was the reason to extract this function if it is not used anywhere?

2021-11-09 21:58 UTC, Darel13712 commented on tests/test_optuna.py
> +    assert res["rank"] != init_rank
Are you sure this will always be true? I think checking the number of tested points in optuna trial would be more reliable.

2021-11-09 21:58 UTC, Darel13712 commented on tests/test_optuna.py
> +    assert res["rank"] != init_rank
This and the following tests are almost exactly the same and I can't grasp what is actually being tested and why the expected result is what it is. Could you please explain?

2021-11-10 08:02 UTC, monkey0head commented on pyproject.toml
> +statsmodels = "*"
it is used for Wilson testing, therefore I moved it to dev dependencies

2021-11-10 08:06 UTC, monkey0head commented on replay/models/base_rec.py
> +                if value < borders[0] or value > borders[1]:
I thought about it but decided complex condition either does not improve readability or creates new local variables. Will change as suggested

2021-11-10 08:16 UTC, monkey0head commented on tests/test_optuna.py
> +    assert res["rank"] != init_rank
well, we do not return optuna study to evaluate the number of tested points and the hyperparameters tested. I already told you that I do not think it is a good decision to do so.

> Are you sure this will always be true? I think checking the number of tested points in optuna trial would be more reliable.
The study has one trial in all the tests. enqueue_trial does not increase budget. I think it is ok, because as a user I expect exactly N runs, not N+1 if some condition met.

> This and the following tests are almost exactly the same and I can't grasp what is actually being tested and why the expected result is what it is. Could you please explain?
If the initial model parameters are outside the search borders, resulting parameters anyway will not be equal to initial.
If the initial model parameters are inside the search borders, first optuna run will be with initial model parameters.

2021-11-10 08:33 UTC, monkey0head commented on replay/optuna_objective.py
> +def eval_quality(
because it names and detaches  a part of code which performs exact functionality. 
it is not necessary here, but it improves readability and makes refactoring easier.
I do not insist

2021-11-10 09:23 UTC, Darel13712 commented on tests/test_optuna.py
> +    assert res["rank"] != init_rank
We do not return study but it is stored in `self.study`.

Ah, I see. If we test only one point it will always be the best.

2021-11-10 09:36 UTC, Darel13712 commented on replay/models/base_rec.py
> +                if value < borders[0] or value > borders[1]:
Well semantically it should be a function that checks whether the value is in or out of bounds, so you can create a separate test for this functionality, but it is only used here so it would be excessive. If you want do the
```
param_out_of_bounds = False
if param_type == "categorical":
    if value not in borders:
        param_out_of_bounds = True
else:
    if value < borders[0] or value > borders[1]:
        param_out_of_bounds = True
if param_out_of_bounds:
    outside_search_space[param] = {
                        "borders": borders,
                        "value": value,
                    }
```
The thing that bothers me is the same code at different if sections.

2021-11-10 11:22 UTC, Darel13712 approved these changes

2021-11-11 08:50 UTC, merged