optuna refactoring
sberbank-ai-lab/RePlay pull request #43
Opened 2021-11-17 13:22 UTC by Darel13712

solves #35
- optimize is refactored
- `param_drid` parameter renamed to `param_borders`
- new tests are significantly faster because they don't call optuna

2021-11-18 09:31 UTC, Darel13712 commented
Note to self: 
- make sure that missing parameters are not initialized with default borders and are not optimized.
- add a docs page explaining what is being optimized when you pass or do not pass arguments, and what happens with initialized model parameters

2021-11-18 15:07 UTC, monkey0head requested changes

2021-11-18 15:16 UTC, Darel13712 commented on .pylintrc
> +disable=bad-option-value,no-else-return
This check is useless. This happens when you do
```python
if condition:
    return a
else:
    return b
```
It forces you to change it to 
```python
if condition:
    return a
return b
```
which is less readable and makes no sense. To avoid creating more disabling lines in code it is better to tune global settings. I'd add the rule that says that `df` does not comply to snake case style there too.

2021-11-18 15:19 UTC, Darel13712 commented on replay/models/base_rec.py
> +            if param not in search_space:
If pass something wrong `param_borders={'lambmbda': [1,2]}` it will not be in search space.

2021-11-18 15:22 UTC, Darel13712 commented on replay/models/base_rec.py
> +            return True
I do not want to say `if outside search space return false. return true`. I want it to be straight `if this than that else that`.

2021-11-18 15:24 UTC, Darel13712 commented on replay/models/base_rec.py
> +        log: Union[Iterable, AnyDataFrame], column: str,
The one we have in `.pre-commit-config.yaml`. `black -l 79`

2021-11-18 15:29 UTC, Darel13712 commented on replay/models/lightfm_wrap.py
> +        self.num_of_warm_users = None
As the commit says, there is a test that runs optimization on a non trained scenario. `optimize` calls `_init_args` which  tries to return these attributes, but they do not yet exist and everything fails.

2021-11-18 15:51 UTC, monkey0head commented on .pylintrc
> +disable=bad-option-value,no-else-return
well, you will not pass programming interview at yandex with this approach

2021-11-18 15:59 UTC, monkey0head commented on replay/models/lightfm_wrap.py
> +        self.num_of_warm_users = None
I was sure you extended model args and added something like "additional_args" in addition to "init_args". it existed for randomRec, as I remember and have disappeared now (
well, let a hundred flowers bloom

2021-11-18 16:01 UTC, monkey0head commented on replay/models/base_rec.py
> +            if param not in search_space:
you have _check_borders function to find these cases

2021-11-18 19:36 UTC, Darel13712 commented on replay/models/base_rec.py
> +            if param not in search_space:
Oh. I was wrong. This is not what's happening here. Here `params` are what is used when you initialize a model. So **all** possible arguments to pass in init. And `search_space` are parameters you want to optimize. Some parameters were not selected for optimization or are not meant to be optimized and this is checked here.

2021-11-24 10:25 UTC, monkey0head requested changes

2021-11-24 10:25 UTC, monkey0head commented on replay/models/base_rec.py
> +        }
too many `param` to understand
is not it better?
```
trial_params = {
            param_name: param_value
            for param_name, param_value in self._init_args.items()
            if param_name in self._search_space
```

2021-11-24 10:25 UTC, monkey0head commented on replay/models/base_rec.py
> +        Checks if param borders are valid and convert them so a search_space format
`to` a search_space format

2021-11-24 10:25 UTC, monkey0head commented on .pylintrc
@AleXXL1986 are you ok with the changes in this file?

2021-11-24 13:40 UTC, monkey0head approved these changes

2021-11-24 18:11 UTC, merged