Relevance in models
sberbank-ai-lab/RePlay pull request #48
Opened 2021-11-25 18:51 UTC by Darel13712

2021-11-26 09:00 UTC, monkey0head requested changes

2021-11-26 09:00 UTC, monkey0head commented on replay/models/random_rec.py
> +                .agg(sf.mean("relevance").alias("probability"))
why is it mean? if an item has one interaction with high score, is the best one? we shall discuss aggregations in PopRec and RandomRec to come to an agreement on calculation formulas

2021-11-26 09:01 UTC, monkey0head commented
pls, add UserPoprec

2021-11-26 09:55 UTC, Darel13712 commented on replay/models/knn.py
> +        :param df: DataFrame with interactions, `[user_idx, item_idx, relevance]`
There is no point calling something log if it's a dataframe and there is no other dataframes around and no need to differentiate them

2021-11-26 09:55 UTC, Darel13712 commented on replay/models/knn.py
> +        norm2 = item_norms.withColumnRenamed(
Similar lines of code are easy to comprehend, long list of chained operations on the other hand is not easy to understand

2021-11-26 09:55 UTC, Darel13712 commented on replay/models/knn.py
> +        df = log.select("user_idx", "item_idx", "relevance")
It doesn't add any meaning, because the user knows that argument name is log and should have a structure. What happens inside is a transformation of that thing and you can clearly see that df is not a random unpredicted data, it is a subset of log with the following columns. It is literally what is written here.

2021-11-26 09:55 UTC, Darel13712 commented on replay/models/pop_rec.py
> +            )
It couldn't be interpreted as probability because random weights do not represent probabilities. But this is possible.

2021-11-26 09:55 UTC, Darel13712 commented on replay/models/pop_rec.py
> +                        "relevance"
This is what was written here all along.

And this only counts unique interactions even if the data contains multiple records.

2021-11-26 09:55 UTC, Darel13712 commented on replay/models/random_rec.py
> +    ValueError: distribution can be one of [popular_based, relevance, uniform]
You cannot have uniform sampling distribution with relevance weighting, because weights wouldn't work at all. And you can't have popularity distribution with relevance weighting because then it won't be a popularity. This parameter changes the training procedure for each of the variants and not a prediction strategy.

2021-11-26 09:55 UTC, Darel13712 commented on replay/models/random_rec.py
> +                .agg(sf.mean("relevance").alias("probability"))
This is what we wanted to add, If you want popularity, then it is old PopRec variant, if it is a proper estimation, then it is Wilson. If you want to use relevance you do this thing with average rating. If you do the thing with the global sum, then very bad item with relevances `[1,1...(x1e10)...1,1]` will be ranked higher than not so popular good item `[5,5]`.  This is not about what is the best item, this is about what ranks higher with given weights.

2021-11-26 09:57 UTC, Darel13712 commented
UserPopRec have no meaning with using weights. It accepts the **number** of interactions per item which is already a weight. One should change this values outside a model

2021-11-26 09:58 UTC, Darel13712 commented on replay/models/knn.py
> +        :param use_relevance: flag to convert relevance to binary form
What should it be instead?

2021-11-26 10:17 UTC, monkey0head commented on replay/models/random_rec.py
> +                .agg(sf.mean("relevance").alias("probability"))
we considered to use this variant with time-based interactions re-weight _or_ any user-defined weights. 
tell how it works for time-based interactions re-weighting now.

2021-11-26 10:26 UTC, monkey0head commented on replay/models/knn.py
> +        :param df: DataFrame with interactions, `[user_idx, item_idx, relevance]`
it is interactions log, not df. I do not we want to force users to go to docstring to realise argument meaning.

2021-11-26 10:27 UTC, monkey0head commented on replay/models/knn.py
> +        norm2 = item_norms.withColumnRenamed(
not here. you only rename columns and do not perform any transformations

2021-11-26 10:30 UTC, monkey0head commented on replay/models/knn.py
> +        df = log.select("user_idx", "item_idx", "relevance")
you better call your `norm2`, `norm1`, `left`, `right`, etc. in this file as df1, df2, df3, df4. cause user do not see them and we can understand the meaning of them from the code

formally speaking,  you reduce readability here and inside _get_similarity_matrix with no point to do so

2021-11-26 10:35 UTC, monkey0head commented on replay/models/random_rec.py
> +    ValueError: distribution can be one of [popular_based, relevance, uniform]
training here should be equivalent to poprec training and inference should remain the same as it was before.

2021-11-26 10:44 UTC, monkey0head commented on replay/models/knn.py
> +        :param use_relevance: flag to convert relevance to binary form
do not know exactly


unary_relevance: flag to convert relevance to unary form
or 
use_relevance: flag to use relevance in item-to-item similarity calculation. If False, all interactions are treated with relevance equal to one

2021-11-26 11:14 UTC, Darel13712 commented on replay/models/knn.py
> +        :param df: DataFrame with interactions, `[user_idx, item_idx, relevance]`
Log is a df. 

And this is inner method. No user shall come here

2021-11-26 11:17 UTC, Darel13712 commented on replay/models/knn.py
> +        norm2 = item_norms.withColumnRenamed(
Column renaming is a transformation by definition. This improves readability.

2021-11-26 11:20 UTC, Darel13712 commented on replay/models/knn.py
> +        df = log.select("user_idx", "item_idx", "relevance")
You completely miss the point of naming variables if you think that log vs df is the same thing as df10 vs variable name. The code became clearer. Not worse

2021-11-26 11:35 UTC, Darel13712 commented on replay/models/random_rec.py
> +    ValueError: distribution can be one of [popular_based, relevance, uniform]
It can't be the same as PopRec, because it changes weights to uniform and Uniform PopRec have no meaning. Having RandomRec independent from PopRec is ok and all the transformations should happen at fit time and not at prediction time. What you suggest is to have multiple predict variants depending on this parameter which is bad.

Also if you read the diff you will see that the inference remains the same as it was before and I didn't change it.

2021-11-26 11:43 UTC, Darel13712 commented on replay/models/random_rec.py
> +                .agg(sf.mean("relevance").alias("probability"))
It works fine, returning random recent items, this is randomrec after all. The sum variant will have more smooth recency distribution and will be more biased towards old popular items whereas this variant will be more biased towards recent items even if they are rated only by one user.

2021-11-26 11:56 UTC, monkey0head commented on replay/models/knn.py
> +        df = log.select("user_idx", "item_idx", "relevance")
both increase entropy without profit, but df10 is worse

2021-11-26 12:12 UTC, Darel13712 commented on replay/models/knn.py
> +        df = log.select("user_idx", "item_idx", "relevance")
Arguably the amount of entropy in this function was greatly reduced.

2021-11-29 09:27 UTC, monkey0head commented on replay/models/knn.py
> +        dot_products = dot_products.withColumn(
I am not sure about this part with `dot_products` redefinition and `norm1/norm2` definition, but it doesn't really matter

2021-11-29 09:28 UTC, monkey0head approved these changes

2021-11-29 14:50 UTC, AleXXL1986 requested changes

2021-11-29 14:50 UTC, AleXXL1986 commented on replay/models/pop_rec.py
> +                .asDict()["relevance"]
let's divide by the user_count. It is faster. In all recommenders we assume that pairs user-item are unique

2021-12-01 07:27 UTC, AleXXL1986 approved these changes

2021-12-01 07:28 UTC, merged