Time smoothing
sberbank-ai-lab/RePlay pull request #50
Opened 2021-12-01 15:30 UTC by Darel13712

Three types of smoothing: power, exponential and linear

2021-12-02 13:00 UTC, AleXXL1986 requested changes

2021-12-02 13:00 UTC, AleXXL1986 commented on replay/time.py
> +    :param decay: number of days after which the weight is reduced by half, must be grater than 1
Why do you use this approach? I think usually users use age and coef

2021-12-02 21:25 UTC, Darel13712 commented on replay/time.py
> +    >>> import pandas as pd
But this is not just random tests. this is a part of documentation

2021-12-02 21:26 UTC, Darel13712 commented on replay/time.py
> +    kind: str = "power",
but why?

2021-12-02 21:26 UTC, Darel13712 commented on replay/time.py
> +    :param decay: number of days after which the weight is reduced by half, must be grater than 1
What approach?

2021-12-02 21:37 UTC, AleXXL1986 commented on replay/time.py
> +    >>> import pandas as pd
yes, but in start of docstring user want to see method description. For example look at pyspark code

2021-12-02 21:39 UTC, AleXXL1986 commented on replay/time.py
> +    :param decay: number of days after which the weight is reduced by half, must be grater than 1
i mean use this decay. it is not intuitive in all cases

2021-12-02 21:41 UTC, AleXXL1986 commented on replay/time.py
> +    kind: str = "power",
because it more logical, and similar on step change in NN

2021-12-02 21:46 UTC, Darel13712 commented on replay/time.py
> +    :param decay: number of days after which the weight is reduced by half, must be grater than 1
Well it is intuitive. And more importantly it is universal for all the methods. do you suggest a user to provide three semantically different parameters under the same name? power or base are easy mathematically but are not intuitive, you won't know how fast it is decreasing, but with decay you know exact point where weight is 0.5

2021-12-05 23:39 UTC, AleXXL1986 approved these changes

2021-12-05 23:40 UTC, merged