test predict for new and cold users
sberbank-ai-lab/RePlay pull request #79
Opened 2022-01-25 17:19 UTC by monkey0head

tests added to check:
- models, which are able to recommend for cold/new users, really do it
- models, which are not able to recommend for cold/new users filter those users out and do not fail

bugs found and fixed:
- cluster model did not filter users in `_predict`
- in neuromf net.forward could return a number instead of tensor for batch of one element as `.squeeze` was used without `dim` parameter

2022-01-27 15:10 UTC, AleXXL1986 requested changes

2022-01-27 15:10 UTC, AleXXL1986 commented on tests/models/test_all_models.py
> +def get_kwargs(model, user_features):
what does the method make?
not so good name

2022-01-28 07:48 UTC, monkey0head commented on tests/models/test_all_models.py
> +def get_kwargs(model, user_features):
it is a function which returns dict with kwargs to pass during models fit and predict.
for models, which use features, it adds user features to kwargs. it helps to run test for all models, whether features are  used or not.

2022-01-28 07:49 UTC, monkey0head commented on tests/models/test_all_models.py
> +def get_kwargs(model, user_features):
deleted

2022-01-28 07:53 UTC, monkey0head commented on tests/models/test_all_models.py
> +    if isinstance(model, LightFMWrap) or not model.can_predict_cold_users:
if we pass user features, lightFM can predict cold users. 
In this test we do not pass user features and look if the model just does not fail and just do not return result for cold/new users.

2022-01-31 08:55 UTC, AleXXL1986 approved these changes

2022-01-31 08:55 UTC, merged