cpp compiler added to installation guide
sberbank-ai-lab/RePlay pull request #83
Opened 2022-01-28 13:45 UTC by monkey0head

#76 reports installation problems during implicit compilation. cpp compiler is required for implicit installation. added to readme

2022-01-31 14:33 UTC, AleXXL1986 requested changes

2022-01-31 14:33 UTC, AleXXL1986 commented on README.md
> +Use Linux machine with Python 3.7+, Java 8+ and C++ compiler.
could you add example with installation compiler?

2022-01-31 16:03 UTC, monkey0head commented on README.md
> +Use Linux machine with Python 3.7+, Java 8+ and C++ compiler.
as discussed I added a new section, dedicated to known installation problems.

2022-01-31 16:06 UTC, monkey0head commented
now this pr changes documentations and thus may be interesting for @Darel13712; added him as a reviewer

2022-01-31 17:18 UTC, Darel13712 approved these changes

2022-02-01 08:08 UTC, AleXXL1986 approved these changes

2022-02-01 08:09 UTC, merged