Fallback cold
sberbank-ai-lab/RePlay pull request #96
Opened 2022-02-09 16:33 UTC by Darel13712

2022-02-14 11:48 UTC, monkey0head commented
max_user max_item is now real maximal idx of user/item (no + 1)

2022-02-16 08:56 UTC, AleXXL1986 requested changes

2022-02-16 08:56 UTC, AleXXL1986 commented on replay/models/admm_slim.py
> +            shape=(self.max_user + 1, self.max_item + 1),
pls add one inside max_user/item (possible you need rename this property to another name)

2022-02-16 16:08 UTC, monkey0head commented
- max_user/item properties renamed to _user_dim/_item_dim private properties.
- 4 new baserec attributes added to store num users/items and user/item dimensions as calling property and calculating each time is computationally expensive
- as we do not have an opportunity to save attributes defined outside __init__,  related properties were left to check the attribute existence and calculate and set it if it is absent.
- caching added for fit_users and fit_items

2022-02-17 08:54 UTC, AleXXL1986 approved these changes

2022-02-17 08:54 UTC, merged